---
- name: preflight checks
  ansible.builtin.include_tasks: "preflight.yml"

- name: prerequisite
  ansible.builtin.include_tasks: "prerequisite.yml"

- name: install envoy
  ansible.builtin.include_tasks: "install.yml"

- name: create envoy config
  ansible.builtin.include_tasks: "config.yml"
