---
- name: preflight checks
  include_tasks: "preflight.yml"

- name: prerequisite
  include_tasks: "prerequisite.yml"

- name: install envoy
  include_tasks: "install.yml"

- name: create envoy config
  include_tasks: "config.yml"

