---
- name: prerequisite | Add the envoy group
  ansible.builtin.group:
    name: "{{ envoy_group }}"
    state: present

- name: prerequisite | Add the envoy user
  ansible.builtin.user:
    name: "{{ envoy_user }}"
    group: "{{ envoy_group }}"
    comment: "envoy proxy"
    system: "{{ envoy_system_user }}"
    createhome: false
    shell: /sbin/nologin
    state: present

- name: prerequisite | create envoy conf directory
  ansible.builtin.file:
    path: "{{ envoy_conf_path }}"
    state: directory
    owner: "{{ envoy_user }}"
    group: "{{ envoy_group }}"
    mode: "0750"
