---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reexec: true

- name: restart envoy
  ansible.builtin.service:
    name: "envoy"
    state: "restarted"
    enabled: true
  when:
    - envoy_systemd
