---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: install xz-utils
      ansible.builtin.package:
        name: "xz-utils"
        state: present
      when: ansible_os_family == "Debian"

    - name: install xz-libs
      ansible.builtin.package:
        name: "xz"
        state: present
      when: ansible_os_family == "RedHat"
